version: '3'
services:
  postgres:
    image: postgres:14.1
    restart: on-failure:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mava-pay-money
    ports:
      - 5442:5432
